security:
  providers:
    ldap:
      id: imag_ldap.security.user.provider
        
  firewalls:
    login:
      pattern: ^/login$
      security: false
     
    restricted_area:
      pattern: ^/
      security: true
      imag_ldap: ~
      logout:
        path:           /logout
        target:         /
              
  encoders:
    IMAG\LdapBundle\User\LdapUser: plaintext

  factories:
    - "%kernel.root_dir%/../src/IMAG/LdapBundle/Resources/config/security_factories.xml"

imag_ldap:
  client:
    host: your.host.foo
    port: 389
#    version: 3 # Optional

  user:
    base_dn: ou=people, dc=host, dc=foo
    filter: (&(foo=bar)(ObjectClass=Person)) #Optional
    name_attribute: uid

  role:
    base_dn: ou=group, dc=host, dc=foo
    filter: null #Optional
    name_attribute: cn
    user_attribute: member
#    user_id: [ dn or username ] #Default dn
